run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gocritic
    - misspell
    - revive
    - exhaustive
    - bodyclose
    - contextcheck
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/nicedavid98/notification-service
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutters
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    - path: tests/
      linters:
        - errcheck
        - unparam
  max-issues-per-linter: 0
  max-same-issues: 0
